<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateUsersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->increments('id');
            $table->timestamp('last_auth')->nullable();
            $table->string('name', 255)->nullable();
            $table->string('email', 255)->nullable();
            $table->string('login_name', 100);
            $table->string('password', 60)->nullable();
            $table->rememberToken();
            $table->integer('photo_last_group_id')->nullable();
            $table->integer('last_event_id')->nullable();
            $table->tinyInteger('blueimp_gallery_controls')->nullable();
            $table->timestamps();
            $table->string('last_reminder_token', 100)->nullable();
            $table->string('group_by', 100)->nullable();

            $table->unique('login_name', 'login_name_unique');

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('users');
    }
}
